In [4]:
a = eval(input("Enter a: "))
b = eval(input("Enter b: "))
print(a+b)

3


In [5]:
fname = input("Enter first name: ")
lname = input("Enter last name: ")
print(fname+ " "+lname)

Abhisek Ray


In [7]:
sname = input("Enter a word")
print(sname.capitalize())

lname = input("Enter another word")
print(lname.capitalize())

Abcd
Efkj


In [9]:
word = "abc-def-dsfk"
final_word = word.split("-")
print(final_word)

['abc', 'def', 'dsfk']


In [10]:
# count vowel in a word
name = "abcdwefwelkjsdfKK"
vow = "aeiouAEIOU"
count = 0
for i in name:
    if i in vow:
        count += 1

print(count)

3


In [11]:
# Put "x" on the place of "c" in a word
str2 = "abcd"
newstr = ""
for i in str2:
    if i == "c":
        newstr += "X"
    else: newstr += i

print(newstr)

abXd


In [12]:
# replace the vowels in a string
word = "skLEIoU"
vowel = "aeiouAEIOU"
for i in word:
    if i in vowel:
        word = word.replace(i,"")

print(word)

skL


In [13]:
string1 = "abcd"
string2 = "ABCD"
print(string1.upper())
print(string2.lower())

ABCD
abcd


In [14]:
word = "abcd1234@#$%"
print(word.isdigit()) #is numeric or not
print(word.isalnum()) #is alpha-numeric or not
print(word.isalpha()) #is alphabet or not

False
False
False


In [15]:
# list
lst = [1,2,3,4,'a','b']
print(lst)

[1, 2, 3, 4, 'a', 'b']


In [18]:
# list separation
lst = ['abc','def','ght']
print(*lst, sep="\n")

abc+def+ght


In [24]:
# sorting method
lst = [1,4,2,54,3,6]
lst.sort()
print(lst)

[1, 2, 3, 4, 6, 54]


In [58]:
# find the median in a list

lst = [1,8,2,3,54,5,89]
lst.sort()
# 1 2 3 5 8 54
size = len(lst)
index = int(size/2)

if(size % 2 != 0):
    median = lst[index]
    print(median)
else:
    median = (lst[index]+lst[index-1])/2
    print(median)

5


In [45]:
lst = [1,2,3,4,5,6]
lst.insert(0,100)
print(lst)

[100, 1, 2, 3, 4, 5, 6]


In [48]:
lst1 = [1,2,3,4]
lst2 = [5,6,7,8]
lst1.extend(lst2)
print(lst1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [62]:
lst = [1,2,3,4,3,4,3,5,6,7]
print(lst.count(3))
print(lst.count(4))

3
2


In [67]:
# dictinary

dct = {}
dct['num'] = [1,2,3]
print(dct)
dct['name'] = ['sa','ab','pu']
print(dct)
dct['items'] = {'num&name': [1,2,3,4,5,6]}
print(dct)

{'num': [1, 2, 3]}
{'num': [1, 2, 3], 'name': ['sa', 'ab', 'pu']}
{'num': [1, 2, 3], 'name': ['sa', 'ab', 'pu'], 'items': {'num&name': [1, 2, 3, 4, 5, 6]}}


In [70]:
dct1 = {'A': 100,'B': 300}
dct2 = {'B': 400, 'C': 600}
print("before update: ",dct1)
dct1.update(dct2)
print("after update: ",dct1)

before update:  {'A': 100, 'B': 300}
after update:  {'A': 100, 'B': 400, 'C': 600}


In [89]:
# write a program to insert the details of 4 students by the following details
# 1. Name : ["ABC","DEF"]
# 2. Roll : [23, 45]
# 3. Stream : ["CSE","ECE"]
# 4. Marks : [78, 76]
# create the dictionary by taking input

std_dict = {'Name': [], 'Roll': [], 'Stream': [], 'Marks': []}
std_num = int(input('Enter the number of students: '))

for i in range(std_num):
   std_dict.get('Name').append(input("enter name: "))
   std_dict.get('Roll').append(input("enter Roll: "))
   std_dict.get('Stream').append(input("enter stream: "))
   std_dict.get('Marks').append(input("enter marks: "))
   # print(std_dict)

print(std_dict)


{'Name': ['Abhisek', 'Satyam', 'Puru'], 'Roll': ['229', '176', '198'], 'Stream': ['enter stream: ', 'enter stream: ', 'enter stream: '], 'Marks': ['50', '80', '45']}


In [99]:
#Array

import numpy as np

list = [1,2,3,4.8,5,6]
print("list: ", list)
array = np.array(list)
print("Array: ", array)


list:  [1, 2, 3, 4.8, 5, 6]
Array:  [1.  2.  3.  4.8 5.  6. ]


In [100]:
list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
