In [12]:
import numpy as np

In [31]:
arr = np.array([10, 2, 30, 4, 50])


print(arr.shape)

(5,)


In [34]:
print("sum of array elements")
print(arr.sum(),"\n")
print("sorted array is")
print(np.sort(arr),"\n")
print("array is sorted order: ", sorted(arr))
print("mean of array elements")
print(arr.mean(),"\n")
print("variance of array elements")
print(arr.var(),"\n")
print("standard deviation of array elements")
print(arr.std(),"\n")
print("median of array elements")
print(np.median(arr))


sum of array elements
96 

sorted array is
[ 2  4 10 30 50] 

array is sorted order:  [2, 4, 10, 30, 50]
mean of array elements
19.2 

variance of array elements
335.36 

standard deviation of array elements
18.312837027615355 

median of array elements
10.0


In [37]:
a1 = np.array([(1,2,3),(4,5,6)])
print("zeroth row: ",a1[0])
print("First row", a1[1])
print("Second Row, two values: ", a1[1, :2])


zeroth row:  [1 2 3]
First row [4 5 6]
Second Row, two values:  [4 5]


In [41]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
z = x[1:3, 1:3] #(row, column)
print("After slicing ,array becomes\n", z)

y = x[1:3, [0,2]]
print("custom slicing ,array becomes\n", y)




After slicing ,array becomes
 [[4 5]
 [7 8]]
custom slicing ,array becomes
 [[3 5]
 [6 8]]


In [51]:
#change the value of the following tuples:

a = [1,2,3,4,6]
a[1] = 200
print(a)

[1, 200, 3, 4, 6]


In [55]:
# boolean indexing and comparison of array

x = np.array([1,2,4,5,6,7,8,9,7,10])
print("The items greater than 5 are")
print(x[x>5])
m = np.array([2,7,4,7,9,4,7]) 
n = np.array([4,6,7,9,1,5,7])
print("Printing the comparison of elements")
print(m>n)


The items greater than 5 are
[ 6  7  8  9  7 10]
Printing the comparison of elements
[False  True False False  True False False]
[False  True False False  True False False]


In [ ]:
# Now Find how many True values u can have in the comparison array for m & n
f = np.array([1,3,5,7])
g = np.array([])
